### ISSUE TITLE
Weird "sprite" and character appearing in the game

### ISSUE THREAD

**Issue by GechaTN1** [pixepchief/evershotrgss3#3]
when i get half through the prototype of this game, i suddenly come across this weird bug/glitch, definitely not supposed to be in this game. the bug has pink hair, wears a cowboy hat, and calls itself "eliza." this is honestly a pretty weird glitch..

This so-called "Eliza" joins your party and fights with you. this is a pretty weird bug but i think it could be fixed if you removed every mention of the name "eliza" from the game, or just removed this "eliza" character entirely. 

**_Thanks! -Gecha_**

**Comment by pixepchief** [comment]
no
